name: Are you a witch
favicon: null
layout_spectrum: 0.7405944317579269
typography_spectrum: 0.842636133544147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6960946598555893
  lightness: 0.9002715973183513
  saturation: 0.8013890632428229
  rhythmicContrast: 0.8009227078873664
purpose: []
