name: Are You a Witch?
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2a29'
    - '#fefefe'
    - '#030305'
    - '#c7c7c7'
    - '#919190'
  brandStrength: 0.5110658020712435
  lightness: 0.8048559683375061
  saturation: 0.2642405757214874
  rhythmicContrast: 0.6170707608107477
purpose: []
